/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author gayatrisk
 */
public class CivilResponseDashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form CivilResponseDashboardPanel
     */
    public CivilResponseDashboardPanel() {
        initComponents();
        setOpaque(false);
    }
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        int w = getWidth(), h = getHeight();
        Color color1 = Color.RED;
        Color color2 = Color.BLACK;
        GradientPaint gp = new GradientPaint(0, 0, color1, w, h, color2);
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, w, h);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblTitleCivilResponseDashboard = new javax.swing.JLabel();
        jBtnActiveDisasters = new javax.swing.JButton();
        jBtnActiveDisasters1 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(179, 0, 8));
        jPanel2.setToolTipText("");
        jPanel2.setAutoscrolls(true);
        jPanel2.setOpaque(false);

        lblTitleCivilResponseDashboard.setFont(new java.awt.Font("Segoe UI Variable", 1, 30)); // NOI18N
        lblTitleCivilResponseDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleCivilResponseDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleCivilResponseDashboard.setText("~ Civil Response Dashboard ~");

        jBtnActiveDisasters.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jBtnActiveDisasters.setForeground(new java.awt.Color(255, 255, 255));
        jBtnActiveDisasters.setText("Active Disasters");
        jBtnActiveDisasters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnActiveDisastersMouseClicked(evt);
            }
        });
        jBtnActiveDisasters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnActiveDisastersActionPerformed(evt);
            }
        });

        jBtnActiveDisasters1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jBtnActiveDisasters1.setForeground(new java.awt.Color(255, 255, 255));
        jBtnActiveDisasters1.setText("All Disasters");
        jBtnActiveDisasters1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnActiveDisasters1MouseClicked(evt);
            }
        });
        jBtnActiveDisasters1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnActiveDisasters1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitleCivilResponseDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnActiveDisasters1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnActiveDisasters, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitleCivilResponseDashboard)
                .addGap(133, 133, 133)
                .addComponent(jBtnActiveDisasters, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jBtnActiveDisasters1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnActiveDisastersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnActiveDisastersActionPerformed
        // TODO add your handling code here:
         MainJFrame.mainPanel.removeAll();
        MainJFrame.mainPanel.add(new CivilResponseActiveDisastersPanel());
        MainJFrame.mainPanel.repaint();
        MainJFrame.mainPanel.revalidate();
    }//GEN-LAST:event_jBtnActiveDisastersActionPerformed

    private void jBtnActiveDisastersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnActiveDisastersMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jBtnActiveDisastersMouseClicked

    private void jBtnActiveDisasters1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnActiveDisasters1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnActiveDisasters1MouseClicked

    private void jBtnActiveDisasters1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnActiveDisasters1ActionPerformed
        // TODO add your handling code here:
        MainJFrame.mainPanel.removeAll();
        MainJFrame.mainPanel.add(new CivilResponseViewAllDisastersPanel());
        MainJFrame.mainPanel.repaint();
        MainJFrame.mainPanel.revalidate();
    }//GEN-LAST:event_jBtnActiveDisasters1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnActiveDisasters;
    private javax.swing.JButton jBtnActiveDisasters1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTitleCivilResponseDashboard;
    // End of variables declaration//GEN-END:variables
}
