/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author Rohit Paul G
 */
public class DisasterReportingJFrame extends javax.swing.JFrame {

    /**
     * Creates new form DisasterReportingJFrame
     */
    public DisasterReportingJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        DisasterToolBar = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        DisasterReportingWorkArea = new javax.swing.JPanel();
        DisasterReporting = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnDisasterWorkspace = new javax.swing.JButton();
        btnSiteManagementWorkspace = new javax.swing.JButton();
        btnReportingManagementWorkspace = new javax.swing.JButton();
        ManageDisasterWorkspace = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        DisasterToolBar.setBackground(new java.awt.Color(255, 218, 220));

        btnExit.setText("Exit");
        btnExit.setOpaque(true);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DisasterToolBarLayout = new javax.swing.GroupLayout(DisasterToolBar);
        DisasterToolBar.setLayout(DisasterToolBarLayout);
        DisasterToolBarLayout.setHorizontalGroup(
            DisasterToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DisasterToolBarLayout.createSequentialGroup()
                .addComponent(btnExit)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DisasterToolBarLayout.setVerticalGroup(
            DisasterToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisasterToolBarLayout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(btnExit)
                .addContainerGap(551, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(DisasterToolBar);

        DisasterReportingWorkArea.setLayout(new java.awt.CardLayout());

        DisasterReporting.setBackground(new java.awt.Color(179, 0, 8));

        lblTitle.setFont(new java.awt.Font("Segoe UI Variable", 1, 30)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("~ Disaster Reporting Dashboard ~");

        btnDisasterWorkspace.setText("Disaster Workspace");

        btnSiteManagementWorkspace.setText("Site Management Workspace");

        btnReportingManagementWorkspace.setText("Reporting Management Workspace");

        javax.swing.GroupLayout DisasterReportingLayout = new javax.swing.GroupLayout(DisasterReporting);
        DisasterReporting.setLayout(DisasterReportingLayout);
        DisasterReportingLayout.setHorizontalGroup(
            DisasterReportingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DisasterReportingLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(170, 170, 170))
            .addGroup(DisasterReportingLayout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addGroup(DisasterReportingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReportingManagementWorkspace)
                    .addComponent(btnSiteManagementWorkspace)
                    .addComponent(btnDisasterWorkspace))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DisasterReportingLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDisasterWorkspace, btnReportingManagementWorkspace, btnSiteManagementWorkspace});

        DisasterReportingLayout.setVerticalGroup(
            DisasterReportingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisasterReportingLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTitle)
                .addGap(163, 163, 163)
                .addComponent(btnDisasterWorkspace)
                .addGap(89, 89, 89)
                .addComponent(btnSiteManagementWorkspace)
                .addGap(88, 88, 88)
                .addComponent(btnReportingManagementWorkspace)
                .addContainerGap(352, Short.MAX_VALUE))
        );

        DisasterReportingWorkArea.add(DisasterReporting, "card2");

        ManageDisasterWorkspace.setBackground(new java.awt.Color(179, 0, 8));

        lblTitle1.setFont(new java.awt.Font("Segoe UI Variable", 1, 30)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("~ Disaster Workspace ~");

        javax.swing.GroupLayout ManageDisasterWorkspaceLayout = new javax.swing.GroupLayout(ManageDisasterWorkspace);
        ManageDisasterWorkspace.setLayout(ManageDisasterWorkspaceLayout);
        ManageDisasterWorkspaceLayout.setHorizontalGroup(
            ManageDisasterWorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageDisasterWorkspaceLayout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(lblTitle1)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        ManageDisasterWorkspaceLayout.setVerticalGroup(
            ManageDisasterWorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageDisasterWorkspaceLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitle1)
                .addContainerGap(801, Short.MAX_VALUE))
        );

        DisasterReportingWorkArea.add(ManageDisasterWorkspace, "card3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 846, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 871, Short.MAX_VALUE)
        );

        DisasterReportingWorkArea.add(jPanel1, "card4");

        jSplitPane1.setRightComponent(DisasterReportingWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisasterReportingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisasterReportingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisasterReportingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisasterReportingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisasterReportingJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DisasterReporting;
    private javax.swing.JPanel DisasterReportingWorkArea;
    private javax.swing.JPanel DisasterToolBar;
    private javax.swing.JPanel ManageDisasterWorkspace;
    private javax.swing.JButton btnDisasterWorkspace;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReportingManagementWorkspace;
    private javax.swing.JButton btnSiteManagementWorkspace;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    // End of variables declaration//GEN-END:variables
}
