/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Disaster.Disaster;
import Disaster.DisasterDirectory;
import static ui.DisasterReportingJFrame.disDir;

/**
 *
 * @author Rohit Paul G
 */
public class DisasterReportingNEWJPanel extends javax.swing.JPanel {
    
    public static DisasterDirectory disDir = new DisasterDirectory();

    /**
     * Creates new form NewJPanel
     */
    public DisasterReportingNEWJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisasterReportingWorkArea = new javax.swing.JPanel();
        DisasterReporting = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnDisasterWorkspace = new javax.swing.JButton();
        btnSiteManagementWorkspace = new javax.swing.JButton();
        btnReportingManagementWorkspace = new javax.swing.JButton();
        ManageDisasterWorkspace = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        lblDisasterId = new javax.swing.JLabel();
        lblDisasterEvent = new javax.swing.JLabel();
        lblDisasterTime = new javax.swing.JLabel();
        lblDisasterDate = new javax.swing.JLabel();
        lblDisasterLocation = new javax.swing.JLabel();
        lblDisasterCoordinates = new javax.swing.JLabel();
        txtDisasterId = new javax.swing.JTextField();
        txtDisasterEvent = new javax.swing.JTextField();
        txtDisasterTime = new javax.swing.JTextField();
        txtDisasterDate = new javax.swing.JTextField();
        txtDisasterLocation = new javax.swing.JTextField();
        txtDisasterCoordinates = new javax.swing.JTextField();
        btnSaveDisaster = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnViewDisaster = new javax.swing.JButton();
        ViewDisasterArea = new javax.swing.JPanel();
        lblTitle2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisasterCollectionjTable = new javax.swing.JTable();
        lblViewDisasterId = new javax.swing.JLabel();
        txtViewDisasterId = new javax.swing.JTextField();
        lblViewDisasterEvent = new javax.swing.JLabel();
        txtViewDisasterEvent = new javax.swing.JTextField();
        lblViewDisasterTime = new javax.swing.JLabel();
        txtViewDisasterTime = new javax.swing.JTextField();
        lblViewDisasterDate = new javax.swing.JLabel();
        txtViewDisasterDate = new javax.swing.JTextField();
        lblViewDisasterLocation = new javax.swing.JLabel();
        txtViewDisasterLocation = new javax.swing.JTextField();
        lblViewDisasterCoordinates = new javax.swing.JLabel();
        txtViewDisasterCoordinates = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        DisasterReportingWorkArea.setLayout(new java.awt.CardLayout());

        DisasterReporting.setBackground(new java.awt.Color(179, 0, 8));

        lblTitle.setFont(new java.awt.Font("Segoe UI Variable", 1, 30)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("~ Disaster Reporting Dashboard ~");

        btnDisasterWorkspace.setText("Disaster Workspace");
        btnDisasterWorkspace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDisasterWorkspaceMouseClicked(evt);
            }
        });

        btnSiteManagementWorkspace.setText("Site Management Workspace");

        btnReportingManagementWorkspace.setText("Reporting Management Workspace");

        javax.swing.GroupLayout DisasterReportingLayout = new javax.swing.GroupLayout(DisasterReporting);
        DisasterReporting.setLayout(DisasterReportingLayout);
        DisasterReportingLayout.setHorizontalGroup(
            DisasterReportingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DisasterReportingLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(170, 170, 170))
            .addGroup(DisasterReportingLayout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addGroup(DisasterReportingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReportingManagementWorkspace)
                    .addComponent(btnSiteManagementWorkspace)
                    .addComponent(btnDisasterWorkspace))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DisasterReportingLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDisasterWorkspace, btnReportingManagementWorkspace, btnSiteManagementWorkspace});

        DisasterReportingLayout.setVerticalGroup(
            DisasterReportingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisasterReportingLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTitle)
                .addGap(163, 163, 163)
                .addComponent(btnDisasterWorkspace)
                .addGap(89, 89, 89)
                .addComponent(btnSiteManagementWorkspace)
                .addGap(88, 88, 88)
                .addComponent(btnReportingManagementWorkspace)
                .addContainerGap(288, Short.MAX_VALUE))
        );

        DisasterReportingWorkArea.add(DisasterReporting, "card2");

        ManageDisasterWorkspace.setBackground(new java.awt.Color(179, 0, 8));

        lblTitle1.setFont(new java.awt.Font("Segoe UI Variable", 1, 30)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("~ Disaster Workspace ~");

        lblDisasterId.setForeground(new java.awt.Color(255, 255, 255));
        lblDisasterId.setText("Disaster ID:");

        lblDisasterEvent.setForeground(new java.awt.Color(255, 255, 255));
        lblDisasterEvent.setText("Disaster Event:");

        lblDisasterTime.setForeground(new java.awt.Color(255, 255, 255));
        lblDisasterTime.setText("Disaster Time:");

        lblDisasterDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDisasterDate.setText("Disaster Date:");

        lblDisasterLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblDisasterLocation.setText("Disaster Location:");

        lblDisasterCoordinates.setForeground(new java.awt.Color(255, 255, 255));
        lblDisasterCoordinates.setText("Disaster Coordinates:");

        txtDisasterId.setOpaque(true);

        txtDisasterEvent.setOpaque(true);

        txtDisasterTime.setOpaque(true);

        txtDisasterDate.setOpaque(true);

        txtDisasterLocation.setOpaque(true);

        txtDisasterCoordinates.setOpaque(true);

        btnSaveDisaster.setText("Save Disaster");
        btnSaveDisaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveDisasterMouseClicked(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        btnViewDisaster.setText("View Disaster");
        btnViewDisaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewDisasterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ManageDisasterWorkspaceLayout = new javax.swing.GroupLayout(ManageDisasterWorkspace);
        ManageDisasterWorkspace.setLayout(ManageDisasterWorkspaceLayout);
        ManageDisasterWorkspaceLayout.setHorizontalGroup(
            ManageDisasterWorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageDisasterWorkspaceLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(ManageDisasterWorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ManageDisasterWorkspaceLayout.createSequentialGroup()
                        .addGroup(ManageDisasterWorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageDisasterWorkspaceLayout.createSequentialGroup()
                                .addGroup(ManageDisasterWorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDisasterCoordinates)
                                    .addComponent(lblDisasterLocation)
                                    .addComponent(lblDisasterTime)
                                    .addComponent(lblDisasterDate)
                                    .addComponent(btnBack))
                                .addGap(45, 45, 45))
                            .addGroup(ManageDisasterWorkspaceLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(ManageDisasterWorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDisasterId)
                                    .addComponent(lblDisasterEvent))
                                .addGap(41, 41, 41)))
                        .addGroup(ManageDisasterWorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSaveDisaster)
                            .addGroup(ManageDisasterWorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDisasterId)
                                .addComponent(txtDisasterEvent)
                                .addComponent(txtDisasterTime)
                                .addComponent(txtDisasterDate)
                                .addComponent(txtDisasterLocation)
                                .addComponent(txtDisasterCoordinates, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                            .addGroup(ManageDisasterWorkspaceLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(btnViewDisaster))))))
        );
        ManageDisasterWorkspaceLayout.setVerticalGroup(
            ManageDisasterWorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageDisasterWorkspaceLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitle1)
                .addGap(94, 94, 94)
                .addGroup(ManageDisasterWorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisasterId)
                    .addComponent(txtDisasterId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(ManageDisasterWorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisasterEvent)
                    .addComponent(txtDisasterEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(ManageDisasterWorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDisasterTime)
                    .addComponent(txtDisasterTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(ManageDisasterWorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDisasterDate)
                    .addComponent(txtDisasterDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(ManageDisasterWorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisasterLocation)
                    .addComponent(txtDisasterLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(ManageDisasterWorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisasterCoordinates)
                    .addComponent(txtDisasterCoordinates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(btnSaveDisaster)
                .addGap(36, 36, 36)
                .addGroup(ManageDisasterWorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnViewDisaster))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        DisasterReportingWorkArea.add(ManageDisasterWorkspace, "card3");

        ViewDisasterArea.setBackground(new java.awt.Color(179, 0, 8));

        lblTitle2.setFont(new java.awt.Font("Segoe UI Variable", 1, 30)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("~ View Disasters ~");

        DisasterCollectionjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(DisasterCollectionjTable);

        lblViewDisasterId.setForeground(new java.awt.Color(255, 255, 255));
        lblViewDisasterId.setText("Disaster ID:");

        txtViewDisasterId.setOpaque(true);

        lblViewDisasterEvent.setForeground(new java.awt.Color(255, 255, 255));
        lblViewDisasterEvent.setText("Disaster Event:");

        txtViewDisasterEvent.setOpaque(true);

        lblViewDisasterTime.setForeground(new java.awt.Color(255, 255, 255));
        lblViewDisasterTime.setText("Disaster Time:");

        txtViewDisasterTime.setOpaque(true);

        lblViewDisasterDate.setForeground(new java.awt.Color(255, 255, 255));
        lblViewDisasterDate.setText("Disaster Date:");

        txtViewDisasterDate.setOpaque(true);

        lblViewDisasterLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblViewDisasterLocation.setText("Disaster Location:");

        txtViewDisasterLocation.setOpaque(true);

        lblViewDisasterCoordinates.setForeground(new java.awt.Color(255, 255, 255));
        lblViewDisasterCoordinates.setText("Disaster Coordinates:");

        txtViewDisasterCoordinates.setOpaque(true);

        btnView.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        javax.swing.GroupLayout ViewDisasterAreaLayout = new javax.swing.GroupLayout(ViewDisasterArea);
        ViewDisasterArea.setLayout(ViewDisasterAreaLayout);
        ViewDisasterAreaLayout.setHorizontalGroup(
            ViewDisasterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewDisasterAreaLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(ViewDisasterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewDisasterAreaLayout.createSequentialGroup()
                        .addComponent(lblTitle2)
                        .addGap(269, 269, 269))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewDisasterAreaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
            .addGroup(ViewDisasterAreaLayout.createSequentialGroup()
                .addGroup(ViewDisasterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewDisasterAreaLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(ViewDisasterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewDisasterAreaLayout.createSequentialGroup()
                                .addGroup(ViewDisasterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblViewDisasterCoordinates)
                                    .addComponent(lblViewDisasterLocation)
                                    .addComponent(lblViewDisasterTime)
                                    .addComponent(lblViewDisasterDate))
                                .addGap(45, 45, 45))
                            .addGroup(ViewDisasterAreaLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(ViewDisasterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblViewDisasterId)
                                    .addComponent(lblViewDisasterEvent))
                                .addGap(41, 41, 41)))
                        .addGroup(ViewDisasterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtViewDisasterId)
                            .addComponent(txtViewDisasterEvent)
                            .addComponent(txtViewDisasterTime)
                            .addComponent(txtViewDisasterDate)
                            .addComponent(txtViewDisasterLocation)
                            .addComponent(txtViewDisasterCoordinates, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ViewDisasterAreaLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnView)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ViewDisasterAreaLayout.setVerticalGroup(
            ViewDisasterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewDisasterAreaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTitle2)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ViewDisasterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(53, 53, 53)
                .addGroup(ViewDisasterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewDisasterId)
                    .addComponent(txtViewDisasterId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(ViewDisasterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewDisasterEvent)
                    .addComponent(txtViewDisasterEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(ViewDisasterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewDisasterTime)
                    .addComponent(txtViewDisasterTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(ViewDisasterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewDisasterDate)
                    .addComponent(txtViewDisasterDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(ViewDisasterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewDisasterLocation)
                    .addComponent(txtViewDisasterLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(ViewDisasterAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewDisasterCoordinates)
                    .addComponent(txtViewDisasterCoordinates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        DisasterReportingWorkArea.add(ViewDisasterArea, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 823, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(DisasterReportingWorkArea, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(DisasterReportingWorkArea, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisasterWorkspaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDisasterWorkspaceMouseClicked
        // TODO add your handling code here:

        DisasterReportingWorkArea.removeAll();
        DisasterReportingWorkArea.add(ManageDisasterWorkspace);
        DisasterReportingWorkArea.repaint();
        DisasterReportingWorkArea.revalidate();
    }//GEN-LAST:event_btnDisasterWorkspaceMouseClicked

    private void btnSaveDisasterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveDisasterMouseClicked
        // TODO add your handling code here:

        Disaster disas = new Disaster();

        disas.setDisasterId(Integer.parseInt(txtDisasterId.getText()));
        disas.setDisasterEvent(txtDisasterEvent.getText());
        disas.setDisasterTime(txtDisasterTime.getText());
        disas.setDisasterDate(txtDisasterDate.getText());
        disas.setDisasterLocation(txtDisasterLocation.getText());
        disas.setDisasterCoordinates(txtDisasterCoordinates.getText());

        disDir.addNewDisaster(disas);

        vanishDataInDisasterCreation();

        //        ArrayList<Disaster> disasterList = DisasterDirectory.getDisasterList();
        //        disasterList.add(disas);

    }//GEN-LAST:event_btnSaveDisasterMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        DisasterReportingWorkArea.removeAll();
        DisasterReportingWorkArea.add(DisasterReporting);
        DisasterReportingWorkArea.repaint();
        DisasterReportingWorkArea.revalidate();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnViewDisasterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewDisasterMouseClicked
        // TODO add your handling code here:
        DisasterReportingWorkArea.removeAll();
        DisasterReportingWorkArea.add(ViewDisasterArea);
        DisasterReportingWorkArea.repaint();
        DisasterReportingWorkArea.revalidate();

    }//GEN-LAST:event_btnViewDisasterMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DisasterCollectionjTable;
    private javax.swing.JPanel DisasterReporting;
    private javax.swing.JPanel DisasterReportingWorkArea;
    private javax.swing.JPanel ManageDisasterWorkspace;
    private javax.swing.JPanel ViewDisasterArea;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDisasterWorkspace;
    private javax.swing.JButton btnReportingManagementWorkspace;
    private javax.swing.JButton btnSaveDisaster;
    private javax.swing.JButton btnSiteManagementWorkspace;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnViewDisaster;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDisasterCoordinates;
    private javax.swing.JLabel lblDisasterDate;
    private javax.swing.JLabel lblDisasterEvent;
    private javax.swing.JLabel lblDisasterId;
    private javax.swing.JLabel lblDisasterLocation;
    private javax.swing.JLabel lblDisasterTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblViewDisasterCoordinates;
    private javax.swing.JLabel lblViewDisasterDate;
    private javax.swing.JLabel lblViewDisasterEvent;
    private javax.swing.JLabel lblViewDisasterId;
    private javax.swing.JLabel lblViewDisasterLocation;
    private javax.swing.JLabel lblViewDisasterTime;
    private javax.swing.JTextField txtDisasterCoordinates;
    private javax.swing.JTextField txtDisasterDate;
    private javax.swing.JTextField txtDisasterEvent;
    private javax.swing.JTextField txtDisasterId;
    private javax.swing.JTextField txtDisasterLocation;
    private javax.swing.JTextField txtDisasterTime;
    private javax.swing.JTextField txtViewDisasterCoordinates;
    private javax.swing.JTextField txtViewDisasterDate;
    private javax.swing.JTextField txtViewDisasterEvent;
    private javax.swing.JTextField txtViewDisasterId;
    private javax.swing.JTextField txtViewDisasterLocation;
    private javax.swing.JTextField txtViewDisasterTime;
    // End of variables declaration//GEN-END:variables

    private void vanishDataInDisasterCreation() {
        txtDisasterId.setText("");
        txtDisasterEvent.setText("");
        txtDisasterTime.setText("");
        txtDisasterDate.setText("");
        txtDisasterLocation.setText("");
        txtDisasterCoordinates.setText("");
        
    }
}
