/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import DataForDisasterAndSiteManagementWorkflow.PopulateDataDisasterAndSiteManagement;
import java.awt.Color;

/**
 *
 * @author rohitpanicker
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        PopulateDataDisasterAndSiteManagement.populateDataDisasterAndSiteManagement();
        configuration.data.PopulateData.populateData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        civilResponseDashboardPanel1 = new ui.CivilResponseDashboardPanel();
        civilResponseActiveDisastersPanel1 = new ui.CivilResponseActiveDisastersPanel();
        civilResponseViewAllDisastersPanel1 = new ui.CivilResponseViewAllDisastersPanel();
        armyEmpDashboardPanel1 = new ui.army.ArmyEmpDashboardPanel();
        armyActiveAssignmentsPanel1 = new ui.army.ArmyActiveAssignmentsPanel();
        armyAllDisasterPanel1 = new ui.army.ArmyAllDisasterPanel();
        armyDashboardPanel1 = new ui.army.ArmyDashboardPanel();
        navyActiveAssignmentsPanel1 = new ui.navy.NavyActiveAssignmentsPanel();
        navyAllDisasterPanel1 = new ui.navy.NavyAllDisasterPanel();
        navyDashboardPanel1 = new ui.navy.NavyDashboardPanel();
        navyEmpDashboardPanel1 = new ui.navy.NavyEmpDashboardPanel();
        policeActiveAssignmentsPanel1 = new ui.police.PoliceActiveAssignmentsPanel();
        policeAllDisasterPanel1 = new ui.police.PoliceAllDisasterPanel();
        policeDashboardPanel1 = new ui.police.PoliceDashboardPanel();
        policeEmpDashboardPanel1 = new ui.police.PoliceEmpDashboardPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 780));
        setUndecorated(true);

        mainPanel.setMaximumSize(new java.awt.Dimension(1200, 800));
        mainPanel.setMinimumSize(new java.awt.Dimension(1200, 800));
        mainPanel.setPreferredSize(new java.awt.Dimension(1200, 800));
        mainPanel.setLayout(new java.awt.CardLayout());
        mainPanel.add(civilResponseDashboardPanel1, "card5");
        mainPanel.add(civilResponseActiveDisastersPanel1, "card6");
        mainPanel.add(civilResponseViewAllDisastersPanel1, "card7");
        mainPanel.add(armyEmpDashboardPanel1, "card8");
        mainPanel.add(armyActiveAssignmentsPanel1, "card6");
        mainPanel.add(armyAllDisasterPanel1, "card7");
        mainPanel.add(armyDashboardPanel1, "card8");
        mainPanel.add(navyActiveAssignmentsPanel1, "card9");
        mainPanel.add(navyAllDisasterPanel1, "card10");
        mainPanel.add(navyDashboardPanel1, "card11");
        mainPanel.add(navyEmpDashboardPanel1, "card12");
        mainPanel.add(policeActiveAssignmentsPanel1, "card13");
        mainPanel.add(policeAllDisasterPanel1, "card14");
        mainPanel.add(policeDashboardPanel1, "card15");
        mainPanel.add(policeEmpDashboardPanel1, "card16");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1218, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginPanel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginPanel2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginPanel2KeyPressed

    private void manageDisasterWorkspacePanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageDisasterWorkspacePanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_manageDisasterWorkspacePanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.army.ArmyActiveAssignmentsPanel armyActiveAssignmentsPanel1;
    private ui.army.ArmyAllDisasterPanel armyAllDisasterPanel1;
    private ui.army.ArmyDashboardPanel armyDashboardPanel1;
    private ui.army.ArmyEmpDashboardPanel armyEmpDashboardPanel1;
    private ui.CivilResponseActiveDisastersPanel civilResponseActiveDisastersPanel1;
    private ui.CivilResponseDashboardPanel civilResponseDashboardPanel1;
    private ui.CivilResponseViewAllDisastersPanel civilResponseViewAllDisastersPanel1;
    public static javax.swing.JPanel mainPanel;
    private ui.navy.NavyActiveAssignmentsPanel navyActiveAssignmentsPanel1;
    private ui.navy.NavyAllDisasterPanel navyAllDisasterPanel1;
    private ui.navy.NavyDashboardPanel navyDashboardPanel1;
    private ui.navy.NavyEmpDashboardPanel navyEmpDashboardPanel1;
    private ui.police.PoliceActiveAssignmentsPanel policeActiveAssignmentsPanel1;
    private ui.police.PoliceAllDisasterPanel policeAllDisasterPanel1;
    private ui.police.PoliceDashboardPanel policeDashboardPanel1;
    private ui.police.PoliceEmpDashboardPanel policeEmpDashboardPanel1;
    // End of variables declaration//GEN-END:variables
}
