/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Disaster.Disaster;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static ui.ManageDisasterWorkspacePanel.disDir;

/**
 *
 * @author Rohit Paul G
 */
public class ViewDisasterPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDisasterPanel
     */
    public ViewDisasterPanel() {
        initComponents();
        populateTable();
        setOpaque(false);
    }
    
    public static void main(String[] args) {
        
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        int w = getWidth(), h = getHeight();
        Color color1 = Color.RED;
        Color color2 = Color.BLACK;
        GradientPaint gp = new GradientPaint(0, 0, color1, w, h, color2);
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, w, h);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DisasterjTable = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        lblDisasterId = new javax.swing.JLabel();
        txtDisasterId = new javax.swing.JTextField();
        lblDisasterEvent = new javax.swing.JLabel();
        txtDisasterEvent = new javax.swing.JTextField();
        lblDisasterTime = new javax.swing.JLabel();
        txtDisasterTime = new javax.swing.JTextField();
        lblDisasterDate = new javax.swing.JLabel();
        txtDisasterDate = new javax.swing.JTextField();
        lblDisasterLocation = new javax.swing.JLabel();
        txtDisasterLocation = new javax.swing.JTextField();
        lblDisasterCoordinates = new javax.swing.JLabel();
        txtDisasterCoordinates = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        DisasterjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Disaster Event", "Diaster ID", "Disaster Time", "Disaster Date", "Disaster Location", "Disaster Coordinates"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(DisasterjTable);

        lblTitle.setFont(new java.awt.Font("Segoe UI Variable", 1, 30)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("~ View Disaster ~");

        btnView.setText("View Disaster");
        btnView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewMouseClicked(evt);
            }
        });

        lblDisasterId.setBackground(new java.awt.Color(255, 255, 255));
        lblDisasterId.setForeground(new java.awt.Color(255, 255, 255));
        lblDisasterId.setText("Disaster ID:");

        lblDisasterEvent.setBackground(new java.awt.Color(255, 255, 255));
        lblDisasterEvent.setForeground(new java.awt.Color(255, 255, 255));
        lblDisasterEvent.setText("Disaster Event:");

        lblDisasterTime.setBackground(new java.awt.Color(255, 255, 255));
        lblDisasterTime.setForeground(new java.awt.Color(255, 255, 255));
        lblDisasterTime.setText("Disaster Time:");

        lblDisasterDate.setBackground(new java.awt.Color(255, 255, 255));
        lblDisasterDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDisasterDate.setText("Disaster Date:");

        lblDisasterLocation.setBackground(new java.awt.Color(255, 255, 255));
        lblDisasterLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblDisasterLocation.setText("Disaster Location:");

        lblDisasterCoordinates.setBackground(new java.awt.Color(255, 255, 255));
        lblDisasterCoordinates.setForeground(new java.awt.Color(255, 255, 255));
        lblDisasterCoordinates.setText("Disaster Coordinates:");

        btnBack.setText("<< Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addGap(126, 126, 126))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDisasterEvent, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDisasterId, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDisasterEvent, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(txtDisasterId)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lblDisasterLocation)
                        .addGap(38, 38, 38)
                        .addComponent(txtDisasterLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDisasterCoordinates)
                        .addGap(38, 38, 38)
                        .addComponent(txtDisasterCoordinates, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDisasterDate)
                            .addComponent(lblDisasterTime))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDisasterTime, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(txtDisasterDate))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(lblTitle)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTitle)
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnBack))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisasterId)
                    .addComponent(txtDisasterId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDisasterTime)
                    .addComponent(txtDisasterTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisasterEvent)
                    .addComponent(txtDisasterEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDisasterDate)
                    .addComponent(txtDisasterDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisasterLocation)
                    .addComponent(txtDisasterLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDisasterCoordinates)
                    .addComponent(txtDisasterCoordinates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(215, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseClicked
        // TODO add your handling code here:
        
        int selectedRowIndex = DisasterjTable.getSelectedRow();
        
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }
        
        Disaster selectedDis = (Disaster)DisasterjTable.getValueAt(DisasterjTable.getSelectedRow(), 0);
        
        //if(disDir.getDisasterList()!= null){
          //  for(Disaster disa : disDir.getDisasterList()){
            //    txtDisasterId.setText(String.valueOf(disa.getDisasterId()));
              //  txtDisasterEvent.setText(disa.getDisasterEvent());
                //txtDisasterTime.setText(disa.getDisasterTime());
                //txtDisasterDate.setText(disa.getDisasterDate());
                //txtDisasterLocation.setText(disa.getDisasterLocation());
                //txtDisasterCoordinates.setText(disa.getDisasterCoordinates());
               
            //}
        //}
        
        txtDisasterId.setText(String.valueOf(selectedDis.getDisasterId()));
        txtDisasterEvent.setText(selectedDis.getDisasterEvent());
        txtDisasterTime.setText(selectedDis.getDisasterTime());
        txtDisasterDate.setText(selectedDis.getDisasterDate());
        txtDisasterLocation.setText(selectedDis.getDisasterLocation());
        txtDisasterCoordinates.setText(selectedDis.getDisasterCoordinates());
        
    }//GEN-LAST:event_btnViewMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        
        MainJFrame.mainPanel.removeAll();
        MainJFrame.mainPanel.add(new ManageDisasterWorkspacePanel());
        MainJFrame.mainPanel.repaint();
        MainJFrame.mainPanel.revalidate();
    }//GEN-LAST:event_btnBackMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DisasterjTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDisasterCoordinates;
    private javax.swing.JLabel lblDisasterDate;
    private javax.swing.JLabel lblDisasterEvent;
    private javax.swing.JLabel lblDisasterId;
    private javax.swing.JLabel lblDisasterLocation;
    private javax.swing.JLabel lblDisasterTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtDisasterCoordinates;
    private javax.swing.JTextField txtDisasterDate;
    private javax.swing.JTextField txtDisasterEvent;
    private javax.swing.JTextField txtDisasterId;
    private javax.swing.JTextField txtDisasterLocation;
    private javax.swing.JTextField txtDisasterTime;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel)DisasterjTable.getModel();
        model.setRowCount(0);
        
        if(disDir.getDisasterList()!= null){
            for(Disaster di : disDir.getDisasterList()){
                Object[] row = new Object[6];
                
                row[0] = di;
                row[1] = di.getDisasterId();
                row[2] = di.getDisasterTime();
                row[3] = di.getDisasterDate();
                row[4] = di.getDisasterLocation();
                row[5] = di.getDisasterCoordinates();
                
                model.addRow(row);
                
            }
            
        }
    }
}
