/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.hospital.cruds;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.hospital.Hospital;
import model.hospital.HospitalDirectory;
import us.state.city.City;
import us.state.city.community.Community;
import utility.ValidationHelper;

/**
 *
 * @author rohitpanicker
 */
public class HospitalCrud extends javax.swing.JPanel {

    /**
     * Creates new form HospitalCrud
     */
    
    public String operation;
    public Hospital hospital;
    private JPanel jpanel = null;
    
    public HospitalCrud() {
        initComponents();
    setOpaque(false);
    }
    
    public HospitalCrud(String operation) {
        
        this.operation = operation;
        
        initComponents();
        setOpaque(false);
    }
    
    public HospitalCrud(Hospital hospital,String operation, JPanel jpanel) {
       
        initComponents();
        setOpaque(false);
        this.operation = operation;
        this.hospital = hospital;
        this.jpanel = jpanel;
         if(operation.equals("populate"))
        {  createDoctorBtn.setVisible(false);
           populateTable(hospital);
        }else if(operation.equals("update"))
        {  createDoctorBtn.setVisible(true);
           createDoctorBtn.setText("Update");
            populateTable(hospital);
            
        }
    }
    
    public HospitalCrud(Hospital hospital,String operation) {
       
        initComponents();
        setOpaque(false);
        this.operation = operation;
        this.hospital = hospital;
         if(operation.equals("populate"))
        {  createDoctorBtn.setVisible(false);
           populateTable(hospital);
        }else if(operation.equals("update"))
        {  createDoctorBtn.setVisible(true);
           createDoctorBtn.setText("Update");
            populateTable(hospital);
            
        }
    }
    
    public void populateTable(Hospital hospital)
    {
         hospitalIdTxtField.setText(String.valueOf(hospital.getHospitalId()));
          nameTxtField.setText(hospital.getHospitalName());
           
             cityTxtField.setText(hospital.getCommunity().getCity().getName());
           stateTxtField.setText(hospital.getCommunity().getCity().getState());
          countryTxtField.setText(hospital.getCommunity().getCity().getCountry());
           
            communityNameTxtField1.setText(hospital.getCommunity().getCommunityName());
           zipCodeTxtField.setText(hospital.getCommunity().getZipCode());
             addressTxtField.setText(hospital.getCommunity().getLocation());

    }
    
    private void clearAllFields() {
       // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    
    hospitalIdTxtField.setText("");
    nameTxtField.setText("");
    communityNameTxtField1.setText("");
    cityTxtField.setText("");
    stateTxtField.setText("");
    countryTxtField.setText("");
    addressTxtField.setText("");
    zipCodeTxtField.setText("");
    
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        int w = getWidth(), h = getHeight();
        Color color1 = Color.RED;
        Color color2 = Color.BLACK;
        GradientPaint gp = new GradientPaint(0, 0, color1, w, h, color2);
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, w, h);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hospitalIdLabel = new javax.swing.JLabel();
        hospitalNameLabel = new javax.swing.JLabel();
        communityNameLabel = new javax.swing.JLabel();
        zipCodeLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        addressTxtField = new javax.swing.JTextField();
        countryLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        hospitalIdTxtField = new javax.swing.JTextField();
        nameTxtField = new javax.swing.JTextField();
        communityNameTxtField1 = new javax.swing.JTextField();
        cityTxtField = new javax.swing.JTextField();
        stateTxtField = new javax.swing.JTextField();
        zipCodeTxtField = new javax.swing.JTextField();
        countryTxtField = new javax.swing.JTextField();
        createDoctorBtn = new javax.swing.JButton();
        logoutLabel = new javax.swing.JLabel();

        jPanel1.setOpaque(false);

        hospitalIdLabel.setText("Hospital ID:");

        hospitalNameLabel.setText("Name:");

        communityNameLabel.setText("Community Name:");

        zipCodeLabel.setText("ZipCode:");

        cityLabel.setText("City:");

        stateLabel.setText("State");

        countryLabel.setText("Country:");

        addressLabel.setText("Address:");

        nameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtFieldActionPerformed(evt);
            }
        });

        createDoctorBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        createDoctorBtn.setText("CREATE");
        createDoctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDoctorBtnActionPerformed(evt);
            }
        });

        logoutLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setText("Logout");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(774, Short.MAX_VALUE)
                .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(hospitalIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(120, 120, 120)
                            .addComponent(hospitalIdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(hospitalNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)
                            .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(communityNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(communityNameTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(150, 150, 150)
                            .addComponent(cityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(stateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(150, 150, 150)
                            .addComponent(stateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(countryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(130, 130, 130)
                            .addComponent(countryTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(addressTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(zipCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(zipCodeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(450, 450, 450)
                            .addComponent(createDoctorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(704, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hospitalIdLabel)
                        .addComponent(hospitalIdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(37, 37, 37)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(hospitalNameLabel))
                        .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(53, 53, 53)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(communityNameLabel))
                        .addComponent(communityNameTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(53, 53, 53)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cityLabel)
                        .addComponent(cityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(57, 57, 57)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(stateLabel)
                        .addComponent(stateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(47, 47, 47)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(countryLabel)
                        .addComponent(countryTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(57, 57, 57)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(addressTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(50, 50, 50)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(zipCodeLabel)
                        .addComponent(zipCodeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addComponent(createDoctorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtFieldActionPerformed

    private void createDoctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDoctorBtnActionPerformed
        // TODO add your handling code here:
        int errorCount = 0;
        StringBuffer errorNotifier = new StringBuffer("Please correct the following Errors\n");
        String id = null, name = null, cityName = null , state = null, country = null, communityName = null, zipCode = null, address = null;

        if(ValidationHelper.isInteger(hospitalIdTxtField.getText())){
            id = hospitalIdTxtField.getText();
        }
        else{
            errorCount++;
            errorNotifier.append(errorCount).append(". Hospital ID should be an Integer\n");
        }

        if(ValidationHelper.isValidName(nameTxtField.getText()))
        {
            name = nameTxtField.getText();
        }else{
            errorCount++;
            errorNotifier.append(errorCount).append(". Hospital Name should be a String\n");
        }

        if(ValidationHelper.isValidName(cityTxtField.getText()))
        {
            cityName = cityTxtField.getText();
        }else{
            errorCount++;
            errorNotifier.append(errorCount).append(". City Name should be a String\n");
        }

        if(ValidationHelper.isValidName(stateTxtField.getText())){
            state = stateTxtField.getText();
        }else{
            errorCount++;
            errorNotifier.append(errorCount).append(". State Name should be a String\n");
        }

        if(ValidationHelper.isValidName(countryTxtField.getText())){
            country = countryTxtField.getText();
        }else{
            errorCount++;
            errorNotifier.append(errorCount).append(". Country Name should be a String\n");
        }

        if(ValidationHelper.isValidName(communityNameTxtField1.getText())){
            communityName = communityNameTxtField1.getText();
        }else{
            errorCount++;
            errorNotifier.append(errorCount).append(". Community Name should be a String\n");
        }
        if(ValidationHelper.isInteger(zipCodeTxtField.getText()))
        {
            zipCode = zipCodeTxtField.getText();
        }else{
            errorCount++;
            errorNotifier.append(errorCount).append(". ZipCode should be an Integer\n");
        }

        if(ValidationHelper.isValidName(addressTxtField.getText())){
            address = addressTxtField.getText();
        }else{
            errorCount++;
            errorNotifier.append(errorCount).append(". Address should be a String\n");
        }

        if(errorCount > 0 )
        {
            JOptionPane.showMessageDialog(this, errorNotifier.toString());
            return;
        }
        else{
            City city = new City(state, country,  cityName);
            Community community = new Community(city, communityName, country, zipCode);
            if(operation.contains("create")){
                Hospital hospital = new Hospital(name, community, Integer.parseInt(id));
                HospitalDirectory.hospitalList.add(hospital);

                JOptionPane.showMessageDialog(this,"Created New Hospital");
                clearAllFields();
            }else if(operation.contains("update"))
            {
                hospital.setCommunity(community);
                hospital.setHospitalId(Integer.parseInt(id));
                hospital.setHospitalName(name);

                JOptionPane.showMessageDialog(this,"Updated Hospital Record Successfulys");
                if(jpanel != null)
                {
                    

                }
                clearAllFields();
            }
        }

    }//GEN-LAST:event_createDoctorBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTxtField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTxtField;
    private javax.swing.JLabel communityNameLabel;
    private javax.swing.JTextField communityNameTxtField1;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryTxtField;
    private javax.swing.JButton createDoctorBtn;
    private javax.swing.JLabel hospitalIdLabel;
    private javax.swing.JTextField hospitalIdTxtField;
    private javax.swing.JLabel hospitalNameLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateTxtField;
    private javax.swing.JLabel zipCodeLabel;
    private javax.swing.JTextField zipCodeTxtField;
    // End of variables declaration//GEN-END:variables
}
