/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.fundraiser;

import Disaster.Disaster;
import Disaster.DisasterDirectory;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.fundraiser.DisasterFundRaiser;
import model.fundraiser.FundRaiserDirectory;
import model.fundraiser.RadioFundRaisingDept;
import model.fundraiser.SocialMediaFundRaisingDept;
import model.fundraiser.TelevisionFundRaisingDept;
import ui.MainJFrame;
import ui.SignupPanel;

/**
 *
 * @author rohitpanicker
 */
public class CreateNewFundRaiserPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewFundRaiserPanel
     */
    
    private static ArrayList<String>currencyList = new ArrayList<>();
    static{
        currencyList.add("INR");
        currencyList.add("USD");
        currencyList.add("EUR");
        currencyList.add("CAD");
        
    }
    public CreateNewFundRaiserPanel() {
       
       initComponents();
       populateComboBox();
       
    }
    
    public void populateComboBox()
    {   
        disasterComboBox.removeAllItems();
        for(Disaster disaster: new DisasterDirectory().getDisasterList())
        {
            disasterComboBox.addItem(disaster.toString());

        }
        
        currencyComboBox.removeAllItems();
        for(String cur: currencyList)
        {
            currencyComboBox.addItem(cur);
        }
        
    }
    
    public static void main(String[] args) {
        
    }

     @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        int w = getWidth(), h = getHeight();
        Color color1 = Color.RED;
        Color color2 = Color.BLACK;
        GradientPaint gp = new GradientPaint(0, 0, color1, w, h, color2);
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, w, h);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        disasterComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        currencyAmountTxtBox = new javax.swing.JTextField();
        currencyComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        televisionCheckBox = new javax.swing.JCheckBox();
        socialMediaCheckBox = new javax.swing.JCheckBox();
        radioCheckBox = new javax.swing.JCheckBox();
        submitBtn = new javax.swing.JButton();

        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Disaster ");

        disasterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        disasterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disasterComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Target");

        currencyAmountTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currencyAmountTxtBoxActionPerformed(evt);
            }
        });

        currencyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Currency");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Publish To:");

        televisionCheckBox.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        televisionCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        televisionCheckBox.setText("Television");
        televisionCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                televisionCheckBoxActionPerformed(evt);
            }
        });

        socialMediaCheckBox.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        socialMediaCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        socialMediaCheckBox.setText("Social Media");
        socialMediaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socialMediaCheckBoxActionPerformed(evt);
            }
        });

        radioCheckBox.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        radioCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        radioCheckBox.setText("Radio");
        radioCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCheckBoxActionPerformed(evt);
            }
        });

        submitBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("SUBMIT");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(disasterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(currencyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(currencyAmountTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(socialMediaCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(televisionCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(disasterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currencyAmountTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currencyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(57, 57, 57)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(televisionCheckBox)
                .addGap(28, 28, 28)
                .addComponent(radioCheckBox)
                .addGap(27, 27, 27)
                .addComponent(socialMediaCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        
        String name = (String) disasterComboBox.getSelectedItem();
        Disaster event = getDisasterEventFromName(name);
        String currency = (String)currencyComboBox.getSelectedItem();
        long amount = Integer.valueOf(currencyAmountTxtBox.getText());
        DisasterFundRaiser fundRaiser = new DisasterFundRaiser(event,currency,amount);
        if(televisionCheckBox.isSelected())
        {
            TelevisionFundRaisingDept.fundRaisingRequest.add(fundRaiser);
        }
        
        if(radioCheckBox.isSelected())
        {
            RadioFundRaisingDept.fundRaisingRequest.add(fundRaiser);
        }
        
        if(socialMediaCheckBox.isSelected())      
        {
           SocialMediaFundRaisingDept.fundRaisingRequest.add(fundRaiser); 
        }
        FundRaiserDirectory.fundRaiserDirectory.add(fundRaiser);
        JOptionPane.showMessageDialog(this, "Fund Raising Request published Successfully");
         MainJFrame.mainPanel.removeAll();
       MainJFrame.mainPanel.add(new DonateFundsPanel());
       MainJFrame.mainPanel.repaint();
       MainJFrame.mainPanel.revalidate();
    }//GEN-LAST:event_submitBtnActionPerformed

    private void radioCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCheckBoxActionPerformed

    private void socialMediaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socialMediaCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_socialMediaCheckBoxActionPerformed

    private void televisionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_televisionCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_televisionCheckBoxActionPerformed

    private void currencyAmountTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencyAmountTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currencyAmountTxtBoxActionPerformed

    private void disasterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disasterComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disasterComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField currencyAmountTxtBox;
    private javax.swing.JComboBox<String> currencyComboBox;
    private javax.swing.JComboBox<String> disasterComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox radioCheckBox;
    private javax.swing.JCheckBox socialMediaCheckBox;
    private javax.swing.JButton submitBtn;
    private javax.swing.JCheckBox televisionCheckBox;
    // End of variables declaration//GEN-END:variables

    private Disaster getDisasterEventFromName(String name) {
        for(Disaster disaster : new DisasterDirectory().getDisasterList())
        {
            if(disaster.getDisasterEvent().equals(name))
            {
                return disaster;
            }
        }
        
        return null;
    }
}
